version: "3.9"

services:
  app:
    build: .
    command: make train
    volumes:
      - ./:/app
      - /home/narek/kaggle/idao/idao_2021_train:/app/data
      - ./generated_submissions:/submissions
    working_dir: /app
